octbem: /home/jihuan/文档/Documents/academic/FEM general/program/fem/ApplyQuadRule.mlb File Reference
/home/jihuan/文档/Documents/academic/FEM general/program/fem/ApplyQuadRule.mlb File Reference
ApplyQuadRule - Apply a quadrature rule to a function.
Functions
function ret = ApplyQuadRule (functor, qpts, qwts, J)
ApplyQuadRule - Apply a quadrature rule to a function.
Detailed Description
ApplyQuadRule - Apply a quadrature rule to a function.
Parameters
functor The function to be integrated, which should have been pulled back onto the reference cell in which the quadrature points are generated. The functor should accept a vector \(x\) as its argument, instead of a list of coordinate components.
qpts A collection of quadrature points, with dimension \(N d\), where \(N\) is the number of points, \(d\) is the space dimension.
qwts A collection of quadrature weights, , with dimension \(N d\), where \(N\) is the number of points, \(d\) is the space dimension.
J The Jacobian, which is a functor, maps from the reference cell to the real cell on which the functor originally is defined.
Function Documentation
ApplyQuadRule()
function ret = ApplyQuadRule (functor, qpts, qwts, J)
ApplyQuadRule - Apply a quadrature rule to a function.
Parameters
functor The function to be integrated, which should have been pulled back onto the reference cell in which the quadrature points are generated. The functor should accept a vector \(x\) as its argument, instead of a list of coordinate components.
qpts A collection of quadrature points, with dimension \(N d\), where \(N\) is the number of points, \(d\) is the space dimension.
qwts A collection of quadrature weights, , with dimension \(N d\), where \(N\) is the number of points, \(d\) is the space dimension.
J The Jacobian, which is a functor, maps from the reference cell to the real cell on which the functor originally is defined.
Referenced by ErichsenQuadCommonEdge(), ErichsenQuadCommonEdgeFlat(), ErichsenQuadRegular(), and ErichsenQuadRegularFlat().